language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=build_docs
    - python: 3.7
      env: TOXENV=pycodestyle
    - python: 3.7
      env: TOXENV=pylint
  allow_failures:
    - env:
      - TOX_ENV=build_docs

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade tox

script:
  - tox

after_success:
  coveralls

after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log
